
_G.AssetsTextureCfg = -- 贴图
{
    ["Currency"] = -- 通用
    {    
        {sName = "grass",   sPath = "assets/textures/grass.png"  },
        {sName = "tc",   sPath = "assets/textures/tc.png"  },
        {sName = "ball",   sPath = "assets/textures/ball.png"  },
        {sName = "hero_001",   sPath = "assets/textures/hero_001.png"  },
        {sName = "hero_002",   sPath = "assets/textures/hero_002.png"  },
        {sName = "hero_ani",   sPath = "assets/textures/hero_ani.png"  },
        {sName = "blueanims",   sPath = "assets/textures/Can Pieces/blueanims.png"  },
        {sName = "blockercans",   sPath = "assets/textures/Can Pieces/blockercans.png"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
        {sName = "timg",   sPath = "assets/textures/timg.jpg"  },
    }, 
}